#!/bin/sh
[ -n "${IPKG_INSTROOT}" ] || {
	( . /etc/uci-defaults/luci-adbyby ) && rm -rf /etc/uci-defaults
	chmod 755 /etc/init.d/adbyby >/dev/null 2>&1
	/etc/init.d/adbyby enable >/dev/null 2>&1
	exit 0
}
