#!/bin/sh /etc/rc.common
START=90
LIST_SEP="
"
CONFIG_TEM="[info]\nid=ar71xx\n[update]"

append_params() {
		local p; local v; local s="$1"; shift
		for p in $*; do
			config_get v config "$p"
			IFS="$LIST_SEP"
			for v in $v; do
				[ -n "$v" ] && (
						echo ""$p"="$v"" | sed -e 's|_|-|g' >> $config_file
				)
			done
			unset IFS
		done
}

append_template(){	
	echo -e $CONFIG_TEM > $config_file
	echo "rule=$rule">> $config_file
	echo -e "\n[cfg]">> $config_file
	echo "listen-address=$listen_address:$listen_port">> $config_file
	echo "buffer-limit=$buffer_limit">> $config_file
	echo "keep-alive-timeout=$keep_alive_timeout">> $config_file
	echo "socket-timeout=$socket_timeout">> $config_file
	echo "max_client_connections=$max_client_connections" >> $config_file
}
start_forward(){
	iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-ports $listen_port
	iptables -t nat -I zone_lan_prerouting -j PREROUTING 
}
stop_forward(){
	iptables -t nat -D zone_lan_prerouting -j PREROUTING  &> /dev/null
	iptables -t nat -F PREROUTING &> /dev/null
	sleep 1
	iptables -t nat -X PREROUTING &> /dev/null
}
start() {
	config_file="/usr/share/adbyby/adhook.ini"
	config_load "adbyby"
	local enabled forward rule listen_address listen_port
	config_get enabled config enabled
	config_get forward config forward
	config_get rule config rule
	config_get listen_address config listen_address
	config_get listen_port config listen_port
	config_get buffer_limit config buffer_limit
	config_get max_client_connections config max_client_connections
	config_get keep_alive_timeout config keep_alive_timeout
	config_get socket_timeout config socket_timeout
	config_get max_client_connections config max_client_connections
	append_template
	local s="$1"
	append_params "$s" \
		buffer_limit keep_alive_timeout socket_timeout
	[ "$enabled" = '0' ] && { 
		return 0
	} 
	/usr/share/adbyby/adbyby &
	[ "$forward" = '0' ] && {
		stop_forward
		return 0
	}
	start_forward
}	
stop() { 
	service_stop /usr/share/adbyby/adbyby
	sleep 1
	stop_forward
}
